/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ItContract } from './ItContract.js';
export * as factories from './factories/index.js';
export { ItContract__factory } from './factories/ItContract__factory.js';